"""Added token blacklist model

Revision ID: 973948348f6e
Revises: 5df0b3d88af4
Create Date: 2024-10-10 13:53:52.493225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973948348f6e'
down_revision = '5df0b3d88af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklisted_token')
    # ### end Alembic commands ###
